// <auto-generated />
using System;
using DatabaseIntegration.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseIntegration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123192422_Changes_v0.01v")]
    partial class Changes_v001v
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseIntegration.Entities.Items.ObtainableItem", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OwnerId");

                    b.HasIndex("ItemId");

                    b.ToTable("ObtainableItems");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.GameAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Nationality")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.GameCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasFilter("[Nickname] IS NOT NULL");

                    b.ToTable("GameCharacters");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.GameCharacterTransform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real");

                    b.Property<float>("RotationW")
                        .HasColumnType("real");

                    b.Property<float>("RotationX")
                        .HasColumnType("real");

                    b.Property<float>("RotationY")
                        .HasColumnType("real");

                    b.Property<float>("RotationZ")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("GameCharacterId")
                        .IsUnique();

                    b.ToTable("GameCharacterTransforms");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.PlayerSkills", b =>
                {
                    b.Property<Guid>("GameCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("GameCharacterId");

                    b.HasIndex("GameCharacterId")
                        .IsUnique();

                    b.ToTable("PlayersSkills");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.PlayerStats", b =>
                {
                    b.Property<Guid>("GameCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CharacterLevelExperiencePoints")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStamina")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxMana")
                        .HasColumnType("int");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("int");

                    b.HasKey("GameCharacterId");

                    b.HasIndex("GameCharacterId")
                        .IsUnique();

                    b.ToTable("PlayersStats");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Items.ObtainableItem", b =>
                {
                    b.HasOne("DatabaseIntegration.Entities.Player.GameCharacter", "Owner")
                        .WithMany("Inventory")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.GameCharacter", b =>
                {
                    b.HasOne("DatabaseIntegration.Entities.Player.GameAccount", "Account")
                        .WithMany("GameCharacters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.GameCharacterTransform", b =>
                {
                    b.HasOne("DatabaseIntegration.Entities.Player.GameCharacter", "GameCharacter")
                        .WithOne("Transform")
                        .HasForeignKey("DatabaseIntegration.Entities.Player.GameCharacterTransform", "GameCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCharacter");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.PlayerSkills", b =>
                {
                    b.HasOne("DatabaseIntegration.Entities.Player.GameCharacter", "GameCharacter")
                        .WithOne("PlayerSkills")
                        .HasForeignKey("DatabaseIntegration.Entities.Player.PlayerSkills", "GameCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCharacter");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.PlayerStats", b =>
                {
                    b.HasOne("DatabaseIntegration.Entities.Player.GameCharacter", "GameCharacter")
                        .WithOne("PlayerStats")
                        .HasForeignKey("DatabaseIntegration.Entities.Player.PlayerStats", "GameCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCharacter");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.GameAccount", b =>
                {
                    b.Navigation("GameCharacters");
                });

            modelBuilder.Entity("DatabaseIntegration.Entities.Player.GameCharacter", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("PlayerSkills");

                    b.Navigation("PlayerStats");

                    b.Navigation("Transform");
                });
#pragma warning restore 612, 618
        }
    }
}
